
cppFiles = Source.cpp Printers\BinaryRamPrinter.cpp Printers\LogisimRamPrinter.cpp AssemblerV3\Lexer.cpp AssemblerV3\Parser.cpp Fileio\FileReader.cpp utils\Radix.cpp

cppFlags = -std=c++20

run:
	g++ $(cppFlags) $(cppFiles) -o AssemblerCPU_t2.exe